make.lua
make/install.lua

在macOS 10.14.4上编译通过.
lni上也有一个PR( https://github.com/actboy168/lni/pull/2 ), 编译时也需要拉取, 等@actboy168 审核通过后, 我也会更新本PR

新增macOS编译支持

---

linux.sh
make.lua
make/install.lua

Support Linux build ; 增加对Linux build的判断;  Linux build needs to link -lstdc++, otherwise it will give error of __gxx_personality_v0 .

support linux build

---

script/workspace.lua

Extend gitignore handling to respect .git/info/exclude

---

script/core/diagnostics/undefined-field.lua
test/diagnostics/init.lua

undefined-field不要检测类型为table的，会出现很多误报

---

script/workspace/workspace.lua

follow-up from #335
With this patch, I can successfully build on nixos :)

Fix workspace logpath to not use ROOT

---

meta/3rd/skynet/config.lua
meta/3rd/skynet/library/skynet.lua
meta/3rd/skynet/library/skynet/cluster.lua
meta/3rd/skynet/library/skynet/crypt.lua
meta/3rd/skynet/library/skynet/db/mongo.lua
meta/3rd/skynet/library/skynet/debug.lua
meta/3rd/skynet/library/skynet/habor.lua
meta/3rd/skynet/library/skynet/muliticast.lua
meta/3rd/skynet/library/skynet/netpack.lua
meta/3rd/skynet/library/skynet/profile.lua
meta/3rd/skynet/library/skynet/sharedata.lua
meta/3rd/skynet/library/skynet/sharemap.lua
meta/3rd/skynet/library/skynet/sharetable.lua
meta/3rd/skynet/library/skynet/socket.lua
meta/3rd/skynet/library/skynet/socketchannel.lua
meta/3rd/skynet/library/skynet/socketdriver.lua
meta/3rd/skynet/library/skynet/stm.lua

This is a skynet meta whick had the save lualib hierarchy of https://github.com/cloudwu/skynet/
The meta's description most came from https://github.com/cloudwu/skynet.wiki.
And some is writed by me, especially the skynet's C librarys.

add skynet meta

---

meta/3rd/skynet/library/skynet.lua

delete some variables not in skynet and alias a skynet message handler

delete some variables not in skynet and alias a skynet message handler

---

meta/3rd/skynet/library/skynet.lua

add some skynet alias and comment

add some skynet alias and comment

---

script/files.lua
script/provider/provider.lua
script/text-merger.lua
test/basic/textmerger.lua

Ensure that cachedRows of files are refreshed after didOpen

---

script/core/hint.lua

Fix Lua › Hint: Param Name == Disable

Fix Lua › Hint: Param Name == Disable

---

meta/3rd/skynet/library/skynet/db/mongo.lua
meta/3rd/skynet/library/skynet/db/mysql.lua

add more skynet function defines

add more skynet function defines

---

script/core/semantic-tokens.lua

a small change ![image](https://user-images.githubusercontent.com/47070852/156606970-cedfdb81-1532-40f8-a18c-7cf91e5ed330.png)

feat(semantic-tokens): mark annotations(@...) as keywords

---

script/provider/diagnostic.lua

Reverts sumneko/lua-language-server#1075

Revert "perf(diagnostic): avoid first send"

---

make/code_format.lua

Fixes https://github.com/sumneko/lua-language-server/issues/1156

Include files required to compile

---

meta/template/basic.lua

#1325: add missing paramter type for getfenv

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
doc/en-us/config.md
doc/pt-br/config.md
doc/zh-cn/config.md
doc/zh-tw/config.md
locale/en-us/script.lua
locale/en-us/setting.lua
locale/pt-br/script.lua
locale/pt-br/setting.lua
locale/zh-cn/script.lua
locale/zh-cn/setting.lua
locale/zh-tw/script.lua
locale/zh-tw/setting.lua
meta/3rd/example/plugin.lua

This PR fixes as many links as I could find to the wiki that would now be broken.

fix: wiki link references

---

README.md

This PR makes the README file a bit prettier and easier to understand.
Can I also suggest changing the description for this repo:
```diff
- Lua Language Server coded by Lua
+ A language server that offers Lua language support - programmed in Lua
```

Make README prettier

---

meta/3rd/luaecs/config.lua
meta/3rd/luaecs/library/ecs.lua
meta/3rd/skynet/config.lua

The luaecs project is:
https://github.com/cloudwu/luaecs

add support of luaecs

---

meta/3rd/love2d/config.json

I added `"love.filesystem.load" : "loadfile"` as a `"Lua.runtime.special"` in `love2d/config.json`.
Fixes #1785.

Implement LOVE: love.filesystem.load should be treated like loadfile #1785

---

script/plugins/ffi/cdefRerence.lua

ci:fix ffi test error

---

meta/template/string.lua

Mark string.find return values as nilable

---

.github/workflows/build.yml

- add musl version build dependency: linux-headers.

---

changelog.md

Changelog item is linking to wrong ticket

Fix link in changelog

---

script/vm/sign.lua

fix: `doc.type.function` resolve only existing arg.extends

---

locale/zh-cn/setting.lua

translated some options to zh-cn

translated some options to zh-cn

---

script/config/template.lua
script/plugin.lua

support multi plugins

---

script/cli/doc.lua

Added 'desc' and 'rawdesc' keys for variables in JSON output.
PR regarding #2520.

Added 'desc' and 'rawdesc' keys for variables in JSON output.

---

script/cli/doc.lua

Added 'visible' key (public, protected, ...) in JSON output.
PR regarding #2516.

Added 'visible' key (public, protected, ...) in JSON output.

---

script/cli/doc.lua

Reverts LuaLS/lua-language-server#2539

Revert "Add "async" key in JSON output."

---

script/cli/doc.lua

Reverts LuaLS/lua-language-server#2538

Revert "Add "deprecated" key in JSON output."

---

script/cli/doc.lua

This PR combines the work done in #2538 and #2539 .

Add "async" and "deprecated" key to JSON output

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/doc-report.yml

Adds another GitHub issue template for reporting a documentation issue.

GitHub issue templates

---

changelog.md
script/core/hint.lua

fix(hint): attempt to index a nil value

---

changelog.md
script/core/definition.lua

Reverts LuaLS/lua-language-server#2792

Revert "fix: improve textDocument/definition ordering"

---

changelog.md
locale/ja-jp/meta.lua
locale/ja-jp/script.lua
locale/ja-jp/setting.lua

Hello, thanks for the great work!
Adding Japanese translations so that I can more confidently suggest this great project to my Japanese friends.
All translations are based on the English text and have been cross-referenced with Chinese translations to ensure that they are accurate.
For now I am skipping the items in `setting.lua` (also skipped in the Portuguese translations), hope that it is fine.

Add Japanese translations

---

changelog.md

Update Love2d version

---

tools/love-api.lua

Added support for typed arrays, here is a diff on what it would look like in action: https://github.com/Luke100000/love2d/commit/4f433d0d0ab678af39fe8116ea8cce33a1947b66

Added support for arrays in meta build tool

---

changelog.md

Fix gcc15 build
