LuaLS/lua-language-server

.gitignore, .gitmodules, make.lua, make/install.lua, make/msvc_crt.lua
构建方法
cd 3rd\luamake && tools\ninja -f ninja\msvc.ninja
3rd\luamake\luamake
TODO:
1. server/bin仍然是旧的代码，应该被移除
2. 其它平台的构建
=> 增加c模块的构建脚本

server/src/uri.lua
这修复了Linux下不能正确写 .vscode/settings.json 的问题. 
原因: linux 下的uri 输入参数是 file:///home/user/project/ 这样(3个斜杠, 包括代表root 的第三个/ ), 而不是 file://// (4个斜杠). 在linux 下用浏览器打开本地文件也是这个形式.
现在linux 下写入.vscode/settings.json 没问题了, 但.vscode/settings.json 更新后(例如更新Lua.diagnostics.globals ),  Problem 下面的警告列表没有马上更新(windows 版本可以). 如果你大概知道会是什么地方的问题, 请提示一下. 谢谢. - John
=> fix linux path uri

osx.sh
fix an issue on macOS.
```
publish (master) ✔ /Users/jiya/workspace/lua-language-server/publish/0.9.8/server/bin/lua-language-server /Users/jiya/workspace/lua-language-server/publish/0.9.8/server/main.lua                                                                           (master|) ✔
/Users/jiya/workspace/lua-language-server/publish/0.9.8/server/bin/lua-language-server: ...kspace/lua-language-server/publish/0.9.8/server/main.lua:8: module 'bee.filesystem' not found:
no field package.preload['bee.filesystem']
no file '/Users/jiya/workspace/lua-language-server/publish/0.9.8/server/src/bee/filesystem.lua'
no file '/Users/jiya/workspace/lua-language-server/publish/0.9.8/server/src/bee/filesystem/init.lua'
no file '/Users/jiya/workspace/lua-language-server/publish/0.9.8/server/bin/bee/fil …
```
=> fix run on macOS

script/method/initialize.lua
Some language server clients like vim-lsp[1] check capabilities more
strictly before enabling them. In this case a missing completionProvider
item in the server capabilities caused completion to not work at all.
[1] https://github.com/prabirshrestha/vim-lsp
=> Add completionProvider to server capabilities

script/method/initialize.lua
Currently the server will send a workspace/workspaceFolders request and
use the first folder that is reported as workspace root.  This doesn't
work with clients that don't support workspaceFolders capability.
The rootUri field of the response to 'initialize' is mandatory and can
be used to create the initial workspace too.  This patch does exactly
this.
=> Create first workspace based on client's rootUri

script/provider/diagnostic.lua
=> 可以通过选项 diagnostics.disable 来禁用语法错误

script/config.lua, script/core/diagnostics/init.lua, script/proto/define.lua
=> 指定诊断类型可以配置只分析打开的文件还是全项目

script/parser/guide.lua, script/parser/luadoc.lua, test/definition/luadoc.lua
目前版本，下面用例会报错。
```
TEST [[
---@class Cat
local <!m!> ---hahaha
---@class Dog
local 	m2
---@type Cat
local <?<!v!>?>
]]
```
因为`---@class Cat`、`---@class Dog` 都绑定到 m2。m 上没有任何绑定。
本 PR 已修复该问题。
=> 处理luadoc在某些情况绑定错误的情况

main.lua
When run follow command with get error message, 
```
$ bin/Linux/lua-language-server  -E main.lua
bin/Linux/lua-language-server: filesystem error: cannot create directories: Permission denied [/log]
```
Which is caused by empty `ROOT` and the folder path for log with be `/log` in follow line,
https://github.com/sumneko/lua-language-server/blob/1458139721646236406825a03a21152d98753515/main.lua#L40
This change try to assign a default value `"."` for `rootPath` to fix the error.
=> [main.lua] fix empty rootPath cause try "/log" folder

script/parser/compile.lua, script/parser/guide.lua, script/parser/luadoc.lua, script/vm/getDocs.lua, test/definition/luadoc.lua, test/example/guide.txt, test/hover/init.lua
相关讨论见 #331
还有个用例需要扩充 simple 信息才能放开
```lua
--TODO 得扩展 simple 的信息才能识别这种情况了
TEST [[
---@class Foo
local Foo = {}
function Foo:bar1() end
---@class Foo2
local Foo2 = {}
function Foo2:<!bar1!>() end
---@type Foo2<number, Foo>
local v1
print(v1.<?bar1?>)
]]
```
=>  添加对 EmmyLua table type 的支持

script/core/guide.lua
The changes by 41ed018e80df12b59cdd0e60cce7484b0c972d81 no longer stopped processing when the main object was already locked. This PR fixes that.
Fixes #496
=> perf: searchSameFields: return early when obj was already locked

script/provider/semantic-tokens.lua
Hi @sumneko ,
The "workspace/semanticTokens/refresh" should be a request according the spec (https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#semanticTokens_refreshRequest).
This change try to correct it and be tested in my local with lsp-mode.
Please help review and merge this change. 
Thanks
=> "workspace/semanticTokens/refresh" should be a request

meta/3rd/OpenResty/library/resty.websocket.client.lua, meta/3rd/OpenResty/library/resty.websocket.lua, meta/3rd/OpenResty/library/resty.websocket.protocol.lua, meta/3rd/OpenResty/library/resty.websocket.server.lua
:wave: 
This PR updates the annotations for [lua-resty-websocket](https://github.com/openresty/lua-resty-websocket), adding docstrings and parameter definitions from the repo. The objects created by `resty.websocket.server` and `resty.websocket.client` are almost the same, so I factored out a lot of the common methods/fields into a class at `resty.websocket`.
I'm new to writing EmmyLua annotations for this language server and don't understand everything yet, so please let me know if there is anything that I should fix regarding formatting, naming conventions, etc. (I think it would be great if there were a contribution/style guide for 3rd party type definitions, to encourage other folks in the community to pitch in).
I do a lot of work on OpenResty, so if you like this PR I will probably …
=> chore: update lua-resty-websocket library annotations

.github/workflows/build.yml
=> Build for linux-arm64

meta/3rd/skynet/library/skynet/db/mongo.lua, meta/3rd/skynet/library/skynet/db/mysql.lua, meta/3rd/skynet/library/skynet/db/redis.lua, meta/3rd/skynet/library/skynet/socketchannel.lua
=> add skynet sc and mongo desc

meta/3rd/OpenResty/library/ngx.balancer.lua, meta/3rd/OpenResty/library/ngx.errlog.lua, meta/3rd/OpenResty/library/ngx.lua, meta/3rd/OpenResty/library/ngx.pipe.lua, meta/3rd/OpenResty/library/ngx.process.lua, meta/3rd/OpenResty/library/ngx.re.lua, meta/3rd/OpenResty/library/ngx.req.lua, meta/3rd/OpenResty/library/ngx.semaphore.lua, meta/3rd/OpenResty/library/ngx.ssl.clienthello.lua, meta/3rd/OpenResty/library/ngx.ssl.lua, meta/3rd/OpenResty/library/ngx.ssl.session.lua, meta/3rd/OpenResty/library/resty.core.regex.lua
There's some new stuff in here:
* added type annotations for `resty.core.regex`
* added some new types/annotations to `ngx`
...but a lot of the work done was just boring cleanup:
* fixed many incorrect function return type annotations
* removed broken markdown links
* removed nonexistent ngx.* functions
* trimmed annotations for readability
* removed extraneous empty lines
* removed many `This API was first enabled in the v0.9.9 release.` types of notes (these are rarely helpful since OpenResty doesn't add new features very often, and they take up lots of screen real estate).
=> update ngx/openresty annotations

script/core/semantic-tokens.lua
Client requests `textDocument/semanticTokens/range` service with a range
parameter in order to get the tokens of the visible window, but server
return the additional comments highlighting tokens may be out of range,
we should keep the tokens requested by the client in range.
=> fix(semantic-tokens): limit comments range

script/core/semantic-tokens.lua
`textDocument/semanticTokens/range` should return `SemanticTokens | null` from LSP specification.
`data` field of the `SemanticTokens` must be a array, even if no result.
=> fix(semantic-tokens): `data` field can't be nil

make/bootstrap.lua
If there is a posix path like `/a/b//c`, the regex pattern to find root directory won't match anything and cause server crashing even if the path is valid. I think windows path also has this problem.
This will happen if someone  add an environment path end with a separator.
```bash
export PATH="$PATH:/path/to/lua-language-server/bin/"
```
This environment path will be used to extend to `package.cpath`. So, `package.cpath` here is `/path/to/lua-language-server/bin//?.so` which the current regex pattern can't recognize.
=> Fix regular expression to find root directory in make/bootstrap.lua

script/provider/provider.lua
Any key in the table of a returned response that has a value of 'nil' will be
excluded from the response's result, and so it needs to be set to
'false'.
In other words, for a textDocument/completion response to include 'isIncomplete' in the result, the table returned in `m.register 'textDocument/complete'` must have `isIncomplete` set to `false`. If it is set to `nil`, then it will be excluded from the response.
`isIncomplete` is a required required parameter in a 'textDocument/completion' response (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionList).
=> Ensure that a completion result has 'isIncomplete'

meta/template/basic.lua
Document add standard library function [newproxy], although they do not appear in the document
=> update meta basic.lua

script/core/semantic-tokens.lua
If metatable with `__call` method, adding `@class` and `@type fun()`
together for a class make the token be regarded as function, we should
make sure `@class` override `@type`.
->
=> fix(semantic-tokens): coreect token type priority

script/core/completion/completion.lua, script/core/noder.lua, test/completion/common.lua, test/type_inference/init.lua
After the fix for #809 landed, Luadoc functions needed to specify the `self` argument if it were meant to be used as an OOP method.
This PR updates the event emitter spec to support `self` and fixes a few crashes / completion issues, such as:
```lua
--- @class EmitFail
--- @field on fun(self, eventName: string, cb: function)
--- @field on fun(self, eventName: '"died"', cb: fun(i: integer))
--- @field on fun(self, eventName: '"won"', cb: fun(s: string))
local emit = {}
emit:on("died", --[[ completion here crashes ]])
emit.on("died", --[[ completion here crashes ]])
```
Before, wrong position for completion:
After fix:
_(Edit)_ I am not familiar with the code architecture, do let me know if there should be any changes !
=> Event emitter support fix

meta/template/debug.lua
class debuginfo miss field  `nparams` and `isvararg`
=> fix meta debuginfo in jit version

.editorconfig
Current project files all use `lf` instead of `crlf`.
=> chore(editorconfig): use lf for end_of_line

script/core/completion/completion.lua, test/completion/common.lua
The callSnippet always expands all the optional arguments and variable
argument that is annoying.
To truncate optional arguments and variable arguments help users more
frequently use `callSnippet`. We already have the label and signature to get
the total arguments.
This behavior is like tsserver.
=> feat(completion): truncate arguments for callSnippet

script/core/completion/postfix.lua
Under Lua code, we should remove redundant placeholders.
Unfortunately, $%d placeholders will result in empty string.
=> chore(postfix): pretty postfix description

script/client.lua
In .luarc, we use key without `Lua.` prefix which is good for completion through schema.
=> fix(client): reuse the previous keys for config

script/provider/diagnostic.lua
If the cache is equal to the full result, we should avoid to notify
client during first stage.
=> perf(diagnostic): avoid first send

locale/en-us/meta.lua
`lua-language-server --check $PWD --checklevel=Hint` is complaining. I am not sure whether the lib should be included while running CLI.
=> fix(template): remove trailing-space

meta/3rd/OpenResty/library/ngx.lua, meta/3rd/OpenResty/library/ngx.re.lua, meta/3rd/OpenResty/library/ngx.ssl.lua, meta/3rd/OpenResty/library/resty.shell.lua, meta/3rd/OpenResty/library/resty.signal.lua, meta/3rd/OpenResty/library/tablepool.lua
This is an incremental update for OpenResty annotations:
* fix some incorrect types
* annotate optional parameters
* refine some type annotations
* annotate new [tcpsock:setclientcert()](https://github.com/openresty/lua-nginx-module#tcpsocksetclientcert) method
* annotate [resty.shell](https://github.com/openresty/lua-resty-shell)
* annotate [resty.signal](https://github.com/openresty/lua-resty-signal)
=> OpenResty annotation updates

make/code_format.lua
Note: This happens on my machine, but not in CI, I did not look into why, but this fixes local compilation.
Ubuntu 21.04
gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Fix for:
```
[59/82] Compile C++ build/obj/code_format/StringUtil.obj
FAILED: build/obj/code_format/StringUtil.obj
gcc -MMD -MT build/obj/code_format/StringUtil.obj -MF build/obj/code_format/StringUtil.obj.d -std=c++17 -O2 -Wall -fvisibility=hidden -I3rd/EmmyLuaCodeStyle/include -I3rd/bee.lua/3rd/lua -DNDEBUG -Wall -Werror -o build/obj/code_format/StringUtil.obj -c 3rd/EmmyLuaCodeStyle/Util/src/StringUtil.cpp
3rd/EmmyLuaCodeStyle/Util/src/StringUtil.cpp:5:10: fatal error: wildcards/match.hpp: No such file or directory
5 | #include "wildcards/match.hpp"
|          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Closes …
=> StringUtil.cpp in EmmyLuaCodeStyle requires wildcards lib

tools/love-api.lua
Since the annotation files for LOVE API are built automatically, I updated the builder. If an argument is of table type its default field is always nil. I added a function that iterates over all the fields in the argument's table field and checks whether all of them have a default value. If so, I assign default = true to the argument. That should make the builder add the needed '?' next to the parameter name in the generated meta file.
See the love-api project's [graphics module](https://github.com/love2d-community/love-api/blob/69e7e015698c0834798a0b9ffeb3a98786b60f1d/modules/graphics/Graphics.lua#L2167-L2188).
=> Alternate fix for #1173

tools/love-api.lua, tools/lovr-api.lua
Summary of changes:
- Made builders add `?` next to argument names if the argument has a default value. 
- `isTableOptional` refactored to `getOptional` that returns `'?'` or an empty string if based on whether the argument is or is not optional. Ready to be inserted in a string with `string.format`. 
The second change is a separate commit and can be reverted if not desired.
=> Add optional flag (?) to overloads in `love2d` and `lovr` builders

meta/3rd/love2d/library/love.data.lua, meta/3rd/love2d/library/love.event.lua, meta/3rd/love2d/library/love.font.lua, meta/3rd/love2d/library/love.graphics.lua, meta/3rd/love2d/library/love.keyboard.lua, meta/3rd/love2d/library/love.math.lua, meta/3rd/love2d/library/love.mouse.lua, meta/3rd/love2d/library/love.physics.lua, meta/3rd/love2d/library/love.thread.lua, tools/love-api.lua
Varargs are now handled properly. I also ran the tool, this caused the other 9 file changes.
This should fix #1182.
=> Added vararg support

locale/en-us/script.lua
=> Fix weird wording for parameter counts

script/core/completion/completion.lua, script/parser/guide.lua, script/vm/compiler.lua, test/completion/common.lua
Add support for auto complete in cases where using an array. A simple example is like these, more in unit tests
```lua
---@alias Option "AAA" | "BBB" | "CCC"
---@type Option[]
local l = {"<??>"}
---@class OptionObj
---@field a boolean
---@field b boolean
---@type OptionObj[]
local l = { {<??>} }
```
these 2 examples will autocomplete with either the expected enum for the first case, or the expected object fields in the second.
Also, I might have screwed up the merge for sub modules, but I think I did it right?
=> Array contents support

meta/3rd/OpenResty/library/cjson.lua, meta/3rd/OpenResty/library/cjson.safe.lua, meta/3rd/OpenResty/library/resty.dns.resolver.lua, meta/3rd/OpenResty/library/string.buffer.lua
* Add `cjson` and `cjson.safe`
-  OpenResty ships with its [own fork of cjson](https://github.com/openresty/lua-cjson) that includes some extra features
* Add `string.buffer`
- this is actually a core luajit extension, but it's relatively new, so I don't know if it's included in other mainstream LuaJIT distros right now.
- https://github.com/openresty/luajit2/blob/v2.1-agentzh/doc/ext_buffer.html
* Update `resty.dns.resolver`
- https://github.com/openresty/lua-resty-dns
=> OpenResty type annotation updates

meta/template/os.lua
The `os.time` function accepts strings as input:
With this small change, it works as expected:
=> Meta: make osdate accept strings

locale/en-us/script.lua
This PR adds en-us descriptions to `locale/en-us/script.lua` for:
- `@operator` from #599
- `@enum` from #1255
=> More tag descriptions

doc/en-us/config.md, doc/pt-br/config.md, doc/zh-cn/config.md, doc/zh-tw/config.md, locale/en-us/setting.lua, locale/pt-br/setting.lua, locale/zh-cn/setting.lua, locale/zh-tw/setting.lua, script/config/template.lua, script/plugin.lua
Adds config.runtime.plugingArgs
Adds pluginPath to package.path. Closes #1297
Adds log.warn() when specified plugin can't be found
Possible Changelog entry:
```txt
* `NEW` `Lua.runtime.pluginArgs`
* `CHG` add plugin path in package.path
```
=> Plugin enchancements

script/core/color.lua, script/provider/provider.lua
Not sure this will really be useful the way it's written right now but it works for my fork and I thought I'd contribute it back upstream in-case this could be used in conjunction with some kind of Color type. 
With some configuration settings it could probably be made useful to others. The hard part is mapping a color to text and back again kinda has to be custom, but we could make some templates that could cover most cases, maybe even as a plugin someone could provide the converting and testing code?
Basically it enables color decorators when it finds a string with 8 hex chars in it's current configuration.
=> add color support

locale/en-us/setting.lua
This PR fixes the missing translation in `locale/en-us/settings.lua` for `config.diagnostics.newfield-call`
Fixes #1015
=> fix #1015 en-us translation

doc/en-us/config.md, doc/pt-br/config.md, doc/zh-cn/config.md, doc/zh-tw/config.md, locale/en-us/setting.lua, locale/pt-br/setting.lua, locale/zh-cn/setting.lua, locale/zh-tw/setting.lua
This PR adds English descriptions for diagnostics which currently do not have one.
=> Missing descriptions for diagnostics

meta/template/utf8.lua
The third parameter `i` of `utf8.offset` should be optional according to Lua Reference Manual, where the definition of it is `utf8.offset (s, n [, i])`.
=> fix inappropriate definition of `utf8.offset`

make/code_format.lua, script/config/template.lua, script/core/diagnostics/param-type-mismatch.lua, script/core/type-formatting.lua
=> 限制typeformat

script/config/template.lua
该功能是基于format_line，当表跨行表达时，在最后一个表项后键入 enter会自动填补逗号。
功能的灵感来自于webstorm在编辑json文件时的行为。
那么该项特性有这么几个问题。
1. 其实现依赖格式化本身的功能，不开format_line无法使用，是否应该独立实现
2. 该特性会不会造成困扰
3. 该特性是否应该默认开启？
=> type format 在键入换行时补全表项的逗号

meta/3rd/OpenResty/library/ngx.lua, meta/3rd/skynet/library/skynet.lua, meta/template/basic.lua, meta/template/coroutine.lua, meta/template/io.lua, meta/template/jit.lua, meta/template/string.lua, script/utility.lua
As discovered in #1539, some of the meta files still use the old `@return` syntax.
This PR serves to fix all the old syntaxes. I do not use any of the third party libraries included by default though so I need some help to figure out what the return types are for those.
=> Replace old variable return syntax

meta/3rd/lfs/config.lua, meta/3rd/lfs/library/lfs.lua
Pattern 'lfs%.%w+' is too greedy.
A script using the 'lfs' always contains string "requre('lfs')",
so new pattern uses 'requre...'
=> Use strict pattern to trigger attaching the lfs library

script/workspace/require-path.lua
When ebabling `pathStrict`, **lua-language-server** properly lists completion for require paths, but can't actually resolve the `require` if it's a strict path from a library.
This PR fixes that.
Any file where the **tail** mathes with a library file and where the relative path in the library is `/`, should be included when **pathStrict** is enabled.
=> fix: pathStrict should also look for strict path uris in workspace libraries

meta/template/ffi.lua
According to the LuaJIT [ffi API reference](https://luajit.org/ext_ffi_api.html#ffi_gc) nil is a valid value for the finalizer.
=> Make second param of ffi.gc optional

meta/3rd/luaecs/library/ecs.lua, meta/3rd/skynet/library/skynet.lua
- user ecs.world() as luaecs words
- remove api sync, singleton
- some api params is optional
=> Update luaecs and skynet API

meta/template/ffi.lua
Fix some behavior in ffi meta 
---
```
---@field [string] function
```
1 - Fixes below issue when C functions are accessed from namespace tables.
---
```
---@overload fun(init?: any, ...): ffi.cdata*
---@overload fun(nelem?: integer, init?: any, ...): ffi.cdata*
```
2 - *`ctype`* isn't a function, it says that `ffi.ctype*` can be called like a constructor [(see Calling a cdata object section)](https://luajit.org/ext_ffi_semantics.html#cdata_call):
> **Calling a cdata object**
**Constructor**: a ctype object can be called and used as a [constructor](https://luajit.org/ext_ffi_api.html#ffi_new). This is equivalent to `ffi.new(ct, ...)`, unless a `__new` metamethod is defined.
---
```
---@class ffi.cb*:    ffi.cdata*
```
3 - `cb` types can only come from `ffi.new` or `ffi.cast`, e.g.: …
=> Fix ffi meta

locale/en-us/script.lua, locale/pt-br/script.lua, locale/zh-cn/script.lua, locale/zh-tw/script.lua, script/core/completion/completion.lua
- Adds completion for `---@package`, `---@private`, `---@protected`.
- Adds descriptions for `---@package`, `---@private`, `---@protected`.
- Updates the description for `---@field` so that the new access modifiers are described.
- Adds temporary descriptions for other locales.
=> Locale additions for 3.6.0

meta/3rd/OpenResty/library/ngx.lua
:wave: small annotation update
---
Both of these are legal (and common in OpenResty code):
```lua
ngx.exit(ngx.HTTP_OK)
ngx.exit(200)
```
=> OpenResty: add plain integer type to ngx.http.status_code

locale/en-us/script.lua
Rewords `en-us` return diagnostics to be more clear.
Was not able to trigger `DIAG_MISSING_RETURN_VALUE_RANGE` or `DIAG_REDUNDANT_RETURN_VALUE_RANGE` to ensure that the descriptions make sense, but I think they do.
Closes #1701
=> fix: en-us return diagnosis descriptions

meta/3rd/OpenResty/library/prometheus.lua
Description by https://github.com/knyar/nginx-lua-prometheus
Usually it will be used by:
```lua
local prometheus = require("prometheus").init("prometheus_metrics")
```
not sure how to type the required module, helps needed.
=> feat: add prometheus

locale/en-us/script.lua, locale/pt-br/script.lua, locale/zh-cn/script.lua, locale/zh-tw/script.lua
Adds literal enum example to `@alias` documentation in English for all languages.
Closes #1685
=> Add literal enum example to `@alias` documentation

script/cli/check.lua
Seems that I have found some bug while trying to use command line for validation.
My settings in  .luarc.json is like this:
```
{
"diagnostics.enable": true,
"diagnostics.groupSeverity": {
"global": "Error",
"strong": "Error",
"type-check": "Error",
"unused": "Error"
},
"diagnostics.severity": {
"spell-check": "Information!",
"trailing-space": "Information!",
"duplicate-doc-alias": "Information!",
},
"runtime.version": "Lua 5.1",
...
}
```
And when I try to start validation I get errors:
```
script\cli\check.lua:56: attempt to compare number with nil
stack traceback:
script\cli\check.lua:56: in upvalue 'callback'
script\lclient.lua:101: in function <script\lclient.lua:100>
stack traceback:
script\lclient.lua:95: in function 'await.errorHandle'
script\await.lua:35: in function …
```
=> Fix validation in CLI if diagnostics.severity contains ...! settings

doc/en-us/config.md, doc/pt-br/config.md, doc/zh-cn/config.md, doc/zh-tw/config.md, locale/en-us/setting.lua, locale/pt-br/setting.lua, locale/zh-cn/setting.lua, locale/zh-tw/setting.lua
This PR adds descriptions for configuration options which do not have one.
=> Descriptions for configuration options

meta/3rd/love2d/library/love/audio.lua, meta/3rd/love2d/library/love/data.lua, meta/3rd/love2d/library/love/event.lua, meta/3rd/love2d/library/love/filesystem.lua, meta/3rd/love2d/library/love/font.lua, meta/3rd/love2d/library/love/graphics.lua, meta/3rd/love2d/library/love/image.lua, meta/3rd/love2d/library/love/joystick.lua, meta/3rd/love2d/library/love/keyboard.lua, meta/3rd/love2d/library/love/math.lua, meta/3rd/love2d/library/love/mouse.lua, meta/3rd/love2d/library/love/physics.lua, meta/3rd/love2d/library/love/sound.lua, meta/3rd/love2d/library/love/system.lua, meta/3rd/love2d/library/love/thread.lua, meta/3rd/love2d/library/love/timer.lua, meta/3rd/love2d/library/love/touch.lua, meta/3rd/love2d/library/love/video.lua, meta/3rd/love2d/library/love/window.lua, tools/love-api.lua
I have added links to from any entity to the wiki, thanks to love2ds naming scheme. I haven't tested all links, however it worked with a class, function and even enums. The big advantage over [LOVE's shortcut](https://marketplace.visualstudio.com/items?itemName=bschulte.love) is that it also works on objects
=> Added links to all love2d functions in documentation

.github/workflows/build.yml
Switch back to Ubuntu 18.04 for building linux releases. This allows for running these on older systems that do not provide GLIBC_2.29.
fix #1828
=> ci: use ubuntu docker container to build linux releases

.github/FUNDING.yml, .github/ISSUE_TEMPLATE/bug-report.yml, README.md, changelog.md, doc/en-us/config.md, doc/pt-br/config.md, doc/zh-cn/config.md, doc/zh-tw/config.md, locale/en-us/script.lua, locale/en-us/setting.lua, locale/pt-br/script.lua, locale/pt-br/setting.lua, locale/zh-cn/script.lua, locale/zh-cn/setting.lua, locale/zh-tw/script.lua, locale/zh-tw/setting.lua, meta/3rd/example/plugin.lua, theme-tokens.md
Updates links that point to `https://github.com/sumneko` to `https://github.com/LuaLS`
=> chore: update links to point to organization

make.sh
- [Wiki](https://github.com/LuaLS/lua-language-server/wiki/Getting-Started#command-line) states you need to `./make.sh` in order to build project, so `make.sh` needs to be executable.
- Using `pushd`/`popd` instead of `cd`
- Using `bash` in order to not mess with cross-shell compabilities
=> Small improvements in make.sh

script/config/template.lua
Moves `addonManager.enable` setting [as requested](https://github.com/LuaLS/vscode-lua/pull/78#issuecomment-1436459125).
=> add: addon manager setting to template

script/vm/compiler.lua, test/crossfile/completion.lua
https: //github.com/LuaLS/lua-language-server/issues/1940
=> Array of a class type does not get completion #1940

meta/template/math.lua
This brings it in line with math.max, and max.min. This change allows the type inference to correctly infer the returned type if math.abs is passed an integer as an argument.
=> Improve math.abs annotation

meta/template/basic.lua
In the Lua 5.1 source code (Lua 5.1.5 lbaselib.c#432-440):
```c
else {
int validproxy = 0;  /* to check if weaktable[metatable(u)] == true */
if (lua_getmetatable(L, 1)) {
lua_rawget(L, lua_upvalueindex(1));
validproxy = lua_toboolean(L, -1);
lua_pop(L, 1);  /* remove value */
}
luaL_argcheck(L, validproxy, 1, "boolean or proxy expected");
lua_getmetatable(L, 1);  /* metatable is valid; get it */
}
```
So `newproxy` can accept a userdata created previously with `newproxy(true)`:
=> meta: newproxy can accept a userdata value

make.lua
Prior to this change, the targets `/main.lua` and `/bootstrap.lua` in `build/build.ninja` were being generated, which in turn caused access violations during the build. I was having problems building on Gentoo because of this (their package manager sandboxes their builds).
To illustrate, here's a diff of `build/build.ninja` generated before and after this change.
```
--- a/build/build.ninja
+++ b/build/build.ninja
@@ -1,6 +1,6 @@
ninja_required_version = 1.7
builddir = build
-bin = bin
+bin = $builddir/bin
obj = $builddir/obj
cc = gcc
luamake = /home/arya/lua-language-server/3rd/luamake/luamake
@@ -109,7 +109,7 @@
command = $cc $in -o $out -lm -ldl -Wl,-E -lstdc++fs -pthread $
-Wl,-Bstatic -lstdc++ -Wl,-Bdynamic -static-libgcc -s
description = Link    Exe $out
-build /bootstrap: …
```
=> Don't override lm.bindir and lm.EXE_DIR in make.lua

locale/en-us/setting.lua, locale/pt-br/setting.lua, locale/zh-cn/setting.lua, locale/zh-tw/setting.lua
Adds a description for `config.addonManager.enable`.
Closes https://github.com/LuaLS/vscode-lua/issues/97
=> add: description for `config.addonManager.enable`

meta/template/string.lua, test/hover/init.lua
All of these functions effectively call `tostring()`, when the passed parameter is a number. I think there is no need to raise warnings if users pass numbers instead of strings to these functions.
You can test this easily online: https://www.lua.org/cgi-bin/demo.
=> Make functions in string api accept numbers

.github/workflows/build.yml
The `musl` version is built with alpine container. Verified on my local repo. 
Naming convention: add `musl` to the final released binaries. such as : `lua-language-server-3.6.18-linux-x64-musl.tar.gz`
=> add support for musl version in github actions

locale/en-us/script.lua, locale/pt-br/script.lua, locale/zh-cn/script.lua, locale/zh-tw/script.lua
Adds links that point to the FAQ to the “too many scanned files” warning. Hopefully this helps guide people to a solution.
Closes #2017
=> fix: add links to too many files warning

script/provider/provider.lua
=> determine the padding

make.sh
I recently introduced this project into my dotfiles, but then I noticed that running `make.sh` ends up adding an alias to my `.zshrc`. The culprit was [this line from `luamake`](https://github.com/actboy168/luamake/blob/295950da763e2bf75956c56fdc7c8c2877aac4ad/compile/install.sh#L35).
The fix to the issue is to not run `install.sh`, but just run `build.sh`
=> fix: do not overwrite config files when building

locale/en-us/script.lua, locale/pt-br/script.lua, locale/zh-cn/script.lua, locale/zh-tw/script.lua
Adds a description for [`@source`](https://github.com/LuaLS/lua-language-server/wiki/Annotations#source), in English, to all locales.
=> add: description for `@source`

script/core/diagnostics/incomplete-signature-doc.lua, test/diagnostics/incomplete-signature-doc.lua
Previously, the diagnostic `incomplete-signature-doc` is ignoring fully undocumented functions - but is already triggered by a simple comment. This turns out to be impractical in a few cases, as it also forces a full documentation of functions that should just be annotated with `---@async` (and is therefore not yet fully compatible with `await-in-sync`)
So this PR adapts the diagnostic to only warn about **incomplete** signature docs, so it requires at least one `@param` or `@return` annotation before a warning is given. (Otherwise, it would be a missing signature doc, and there's separate diagnostics about that...)
=> Adapt incomplete-signature-doc to warn about incomplete, not missing docs

locale/en-us/script.lua, script/core/code-action.lua, script/core/command/autoRequire.lua, script/core/diagnostics/undefined-global.lua, script/vm/global.lua, script/vm/node.lua, test/code_action/init.lua
I attempted to implement #1938.
This is how it looks in action:
How to make this less of a hack?
https://github.com/LuaLS/lua-language-server/blob/62d4d35faf325788355ea9854bee54383db5acdb/script/core/code-action.lua#L730-L739
How to add tests? I suppose they should go somewhere here:
https://github.com/LuaLS/lua-language-server/blob/62d4d35faf325788355ea9854bee54383db5acdb/test/code_action/init.lua#L158
But how do I create the stubs for other modules?
=> [Feature] Add action to autorequire undefined globals

changelog.md, meta/template/string.lua
Fixes #2224. I hope I figured out the syntax used in these templates correctly.
Note:
- LuaJIT also [includes](https://luajit.org/extensions.html) the strip argument for `string.dump`.
=> Update `string.dump` so it doesn't have strip argument in Lua 5.1 and 5.2

meta/template/os.lua
=> fix: os.time optionals

.github/ISSUE_TEMPLATE/bug-report.yml, README.md, changelog.md, doc/en-us/config.md, doc/pt-br/config.md, doc/zh-cn/config.md, doc/zh-tw/config.md, locale/en-us/script.lua, locale/en-us/setting.lua, locale/pt-br/script.lua, locale/pt-br/setting.lua, locale/zh-cn/script.lua, locale/zh-cn/setting.lua, locale/zh-tw/script.lua, locale/zh-tw/setting.lua, meta/3rd/example/plugin.lua
Replaces references to the old wiki with references to the [new wiki](https://luals.github.io/wiki).
Not quite sure what to do for the below instances, as they haven't existed in a long while, as far as I can tell:
https://github.com/LuaLS/lua-language-server/blob/63211177f8f3ad2a50dca3ab2ccaae737486813c/changelog.md?plain=1#L879
https://github.com/LuaLS/lua-language-server/blob/63211177f8f3ad2a50dca3ab2ccaae737486813c/changelog.md?plain=1#L1046
~~https://github.com/LuaLS/lua-language-server/blob/63211177f8f3ad2a50dca3ab2ccaae737486813c/locale/en-us/setting.lua#L283-L289~~
=> chore: replace wiki references

script/core/diagnostics/cast-local-type.lua
The `unused-local` diagnostic already hard-codes to exclude `_`.
`cast-local-type` should also ignore `_` variables, to avoid warnings
in, for example, nested loops like:
```lua
for _, list in ipairs(lists) do
for _, item in ipairs(list) do
_, result = pcall(...)
end
end
```
=> Ignore `cast-local-type` diagnostic for `_` local

locale/en-us/meta.lua, locale/pt-br/meta.lua, locale/zh-cn/meta.lua, locale/zh-tw/meta.lua
This updates `meta.lua` to fix the minimum versions on several `math` attributes that did not exist prior to Lua 5.3.
I followed samples from the surrounding code, but I'm not sure if I formatted these correctly.
=> set min version for some math.* functions

locale/en-us/script.lua
In the following example:
```lua
---@param t { x: integer }
local function test(t)
t.w = 1
end
```
I get this message:  Fields cannot be injected into the reference of `{ x: integer }` for `w`. 如要允许注入，请在定义中添加 `[any]: any` 。
I translated the message after checking Google Translate and DeepL. I also fixed a couple of typos and removed outdated translation TODOs.
=> Translate table injection diag and fix some issues

script/core/completion/completion.lua, test/completion/common.lua
Currently LuaLS will expand:
```lua
---<??>
local x = function (x, y) end
```
with:
```lua
---comment
---@param x any
---@param y any
local x = function (x, y) end
```
This change adds a variation of this snippet to expand:
```lua
--- <??>
local x = function (x, y) end
```
with:
```lua
--- comment
--- @param x any
--- @param y any
local x = function (x, y) end
```
=> feat: support param snippets with space

.editorconfig
The [EditorConfig specification](https://spec.editorconfig.org/#supported-pairs) does not support "auto" as a value for "end_of_line". EditorConfig implementations which adhere to the specification (such as Neovim) will either ignore this value or, worse, show a warning or error to the user. Simply omitting `end_of_line` will use the default end of line value for the platform.
Git (and other source control tools) can handle translating end of line characters between Windows and Unix platforms. The `end_of_line` option is there _only_ when you want to maintain a strict end of line character *across* platforms.
=> Do not use off-spec value for end_of_line

script/cli/check.lua, script/global.d.lua
This allows customizing where the diagnostic JSON file is saved.
=> Add `--check_out_path` CLI argument

doc/en-us/config.md, doc/pt-br/config.md, doc/zh-cn/config.md, doc/zh-tw/config.md, script/config/template.lua, script/library.lua
This lets you skip the "apply third party library to workspace configuration" prompt.
The value of `Lua.workspace.checkThirdParty` can now be one of:
* `Ask` (ask every time; this is equivalent to `true`)
* `Apply` (always apply third-party libraries and set the workspace
configuration)
* `ApplyInMemory` (always apply third-party libraries but don't set the
workspace configuration)
* `Disable` (don't ask and don't apply; this is equivalent to `false`)
Backwards compatibility with the old boolean configuration values is maintained; `true` is treated as `Ask` and `false` is treated as `Disable`.
I need some help translating the Taiwanese, Mandarin, and Portugese, but I copied the English in there as a standin -- presumably it's better to have some documentation in the wrong language which …
=> Make `workspace.checkThirdParty` a string enum

script/library.lua
I attempted to maintain backwards compatibility in #2354 but didn't fully understand the config type system. Here I checked for the booleans `true` and `false`:
https://github.com/LuaLS/lua-language-server/blob/3bbc8dd579dadd67171c758c1065f271c5816133/script/library.lua#L611-L617
But the config value is now defined as a string:
https://github.com/LuaLS/lua-language-server/blob/5a763b0ceecc9a817c8ce534dc726f5f6f6e1ac9/script/config/template.lua#L320-L325
So when the config is loaded as a boolean, it gets converted to a string:
https://github.com/LuaLS/lua-language-server/blob/5a763b0ceecc9a817c8ce534dc726f5f6f6e1ac9/script/config/template.lua#L81-L85
We can fix this by checking for the string values `'true'` and `'false'`, rather than the boolean values `true` and `false`.
=> Fix backwards compatability with `Lua.workspace.checkThirdParty`

script/config/template.lua, script/library.lua
I attempted to maintain backwards compatability in https://github.com/LuaLS/lua-language-server/pull/2354 and https://github.com/LuaLS/lua-language-server/pull/2406 but didn't fully understand the config type system.
This approach uses `Type.Or` and I even tested it to confirm that it works!
Thanks to @pysan3 for pointing out how a default would be used for invalid types (https://github.com/LuaLS/lua-language-server/pull/2406#issuecomment-1802337591), and thanks to @sumneko for pointing out `Type.Or` (https://github.com/LuaLS/lua-language-server/pull/2406#issuecomment-1802353877).
=> Fix backwards compatability with `Lua.workspace.checkThirdParty` (take 2!)

meta/template/bit.lua
LuaJIT's `bit.tohex` returns a string value of the decimal number formatted as a hexadecimal not an integer value.
=> bit meta: tohex returns a string

script/core/completion/completion.lua
Place a space between `---` and `@return` when generating documentation for a function on a line like `--- `. This mimics how `@param` documentation is generated.
=> Pad `return` type annotations when required.

script/files.lua, script/parser/guide.lua, script/parser/init.lua, script/parser/luadoc.lua, script/plugins/astHelper.lua, test.lua, test/full/example.lua, test/plugins/ast/init.lua
Allow plugins can adjust ast.
OnSetText is too limited.It can be noted that the paradigm of lua is too complex, and perhaps some of the work can be left to the plugin authors
=> plugin: add OnTransformAst interface

meta/template/table.lua
LuaJIT supports `table.move()`: https://luajit.org/extensions.html#lua53
=> Add `table.move()` to LuaJIT compatibility

script/cli/init.lua, script/cli/visualize.lua, test.lua, test/cli/test.lua, test/cli/visualize/test.lua, test/cli/visualize/testdata/all-types-expected.txt, test/cli/visualize/testdata/all-types.txt, test/cli/visualize/testdata/shorten-names-expected.txt, test/cli/visualize/testdata/shorten-names.txt
Quick script I wrote while writing an AST-based plugin, it turned out to be immensely helpful for me while trying to learn the AST format. I hope it is equally helpful for others.
Example graph from the test:
Edit: GitHub absolutely destroys the SVG I uploaded. Copy & paste the contents of test/cli/visualize/testdata/all-types-expected.txt here to see what this does https://dreampuf.github.io/GraphvizOnline/
=> Add --visualize command that outputs the AST of a given file as graphviz

script/parser/luadoc.lua, script/plugins/astHelper.lua, test/plugins/ast/test.lua
This allows binding multiple generated luadoc annotations to a single node easily by explicitly specifying their bind group.
=> Add group param for luadoc generated by plugins

script/cli/doc.lua, script/global.d.lua
CLI option --doc_out_path <PATH>.
This CLI option specifies the output directory path for documentation files (eg. 'doc.json').
=> CLI option --doc_out_path <PATH>.

script/parser/luadoc.lua, script/vm/infer.lua, test/diagnostics/assign-type-mismatch.lua, test/hover/init.lua
Support annotation of tuples by using square brackets.
```lua
---@type [string, integer]
```
=> support tuple type

script/cli/check.lua, script/plugin.lua
Diagnostics reports provided by `lua-language-server --check .` currently does not use plugins.
For some complex projects, plugins are required for proper type annotations.
To fix this:
1. require plugin to add the 'startReload' / 'initPlugin'  callback to the workspace watchlist
2. in a previous PR, pluginargs was changed to support multiple plugins.  Previously it had 1 default type, but now it has 2.  This means that the default `get` returns nil instead of an empty table.  To smooth this transition, I set it to `{}` when it is `nil`.
=> Enable plugins during --check

script/cli/check.lua
The current behavior of --check is to run diagnostics on all files that are loaded including defined libraries. I believe checking libraries is undesirable because:
1. you might not own the code in there and any warning triggered in there can be non-actionable for you
2. libraries can be very large and make check take a long time. For our project it adds about 2 minutes of time to check libraries and get warnings we can't do anything about anyways
Please let me know if you would prefer this behavior to be customizable instead, but I believe the current behavior is just undesirable in general.
=> Only load files in workspace for --check (skip libraries)

script/cli/check.lua
stdout is often line-buffered and needs flushing for the progress indicator to work
=> Flush stdout in check progress indicator

meta/3rd/example/config.json
I noticed a typo in meta/3rd/example/config.json while figuring out how to add the Scrap Mechanic library in Kate
This is my first pull request, so if I did anything wrong please let me know
=> Fix typo in config.json

script/plugin.lua, script/workspace/require-path.lua
This PR allows plugins to manually resolve `require('...')` file paths. It adds `ResolveRequire` plugin method, that accepts workspace URI and require name, and can return resolved paths to Lua files.  
This feature would be helpful for environments that implement custom `require` name resolution, as it provides max flexibility and can be added with an addon.
```lua
---@param uri string
---@param name string
---@return nil|string[]
function ResolveRequire(uri, name)
if name:byte(1) ~= 0x40 --[['@']] then
return nil
end
return { "file:///path/to/mods/" .. name:sub(2) .. "/main.lua" }
end
```
=> Allow plugins to resolve require paths

script/core/diagnostics/discard-returns.lua, test/diagnostics/discard-returns.lua
Fixed the https://github.com/LuaLS/lua-language-server/issues/2549 by extending the support for all block types. Tests included.
=> Detect discard-returns in all block types

meta/template/basic.lua
Fixes #1353
Not sure if this is the best way to fix this problem, but it does remove many false diagnostics from our codebase.
=> meta: improve typing for unpack

script/core/diagnostics/init.lua, script/provider/diagnostic.lua, script/provider/provider.lua
If I explicitly click on "Diagnose workspace" I would expect it to show me *all* the diagnostics similar to how --check in a CI would check my project.
This makes it easier for users to check their whole workspace after making changes to some library or core function that potentially affects a large number of files that are usually only checked once opened.
=> Run diagnostics on unopened files when explicitly requested by the user

.github/workflows/build.yml
There were errors when running build workflow for linux-arm64, and no linux-arm64 binaries were built since 3.8.0 (#2626).
The build workflow can be fixed by using sudo for apt-get commands.
=> Fix linux-arm64 build

locale/en-us/script.lua, locale/pt-br/script.lua, locale/zh-cn/script.lua, locale/zh-tw/script.lua, script/cli/check.lua, script/cli/check_worker.lua, script/cli/init.lua
Set the parameter --num_threads to the desired number of worker tasks to potentially speed up --check.
This works by spawning multiple sub-proccesses that each run the desired diagnostics on a subset of the workspace. Each process will still load and compile the entire workspace, so there are diminishing returns and memory usage increases linearly with the number of threads.
Overall this can reduce the runtime by about ~50% for my projects, example results:
Workspace 1, dominated by a few large/complex files
1 thread:  49.7 seconds
2 threads: 31.8 seconds
4 threads: 23.6 seconds
8 threads: 24.4 seconds
Workspace 2, large number of small-ish files
1 thread:  96.0 seconds
2 threads: 76.5 seconds
4 threads: 49.5 seconds
8 threads: 38.1 seconds
=> Add multi-process support to --check.

doc/en-us/config.md, doc/pt-br/config.md, doc/zh-cn/config.md, doc/zh-tw/config.md, locale/en-us/setting.lua, locale/pt-br/setting.lua, locale/zh-cn/setting.lua, locale/zh-tw/setting.lua, script/config/template.lua, script/core/diagnostics/global-element.lua, script/core/diagnostics/lowercase-global.lua, script/vm/global.lua
I use the LuaLS for many years and all of these years I had disabled the undefined-global because my project use global envs, and in these envs I have some globals like "const_something" and "SOMETHING" in more than 1000 submodules. So I needed this feature to improve my project checking.
I also improved to avoid unecessary checks in checkIsUndefinedGlobal like create a table with all elements to check only one of them.
This is related to: https://github.com/LuaLS/lua-language-server/issues/2627
Exemple of config:
```
"Lua.diagnostics.globalsRegex": [
"^const.*",
"^[A-Z][A-Z0-9_]+$",
],
```
=> Add setting to find globals using regex

main.lua, script/config/env.lua
This started off with me taking a look at implementing https://github.com/LuaLS/lua-language-server/issues/2330, but I am not sure how I would go about merging an ENV variable with a client configuration. Any tips on that would be great!
In the meantime, I have added loading of ENV variables for a bunch of the CLI args, as it was a pretty low-hanging fruit. So for example, instead of doing `./lua-language-server --doc="path/to/workspace"`, you can do `export LLS_DOC_PATH="path/to/workspace"` and then just run `./lua-language-server`.
=> add: load ENV variables as args

.github/workflows/build.yml, Dockerfile
Similar fix to #1835, but uses independent docker environment instead of GitHub Workflow container. Fixes the issue #1828.
The `action/checkout@v4` uses `node20` depends on newer GLIBC version, which is not available in old docker image, e.g., `ubuntu-18.04`. We don't want the image has newer version of glibc because we want to build binary using older version of GLIBC. Because the container will be evoked at start of the job, using `action/checkout@v4` causes the [errors](https://github.com/LuaLS/lua-language-server/actions/runs/7967876039/job/21751273480). Therefore, moving build steps into independent docker environment is the easiest way to build with old GLIBC version, and not affecting the GitHub Workflow.
=> build: use docker to build linux-x64 glibc

script/cli/check_worker.lua
This makes --check about 25% faster.
=> Disable await.delay() when running --check

.github/scripts/check-changelog.sh, .github/workflows/changelog.yml, changelog.md
This PR adds a workflow that checks incoming PRs for changelog changes, failing if no changes were made.
Another important change is that the [changelog should always contain an “Unreleased” section](https://keepachangelog.com/en/1.1.0/#effort) at the top, so it is easy to add all new changes there between releases. When it is time for a new release, the points from under “Unreleased” are simply moved under a version number.
This should help prevent new changes from going under the radar.
@sumneko **I have also edited the branch protection rules on `master`** so that in order for a pull request to be merged, this changelog edit check **must** succeed before merging, although admins can still override it and merge regardless.
=> add: workflow to assert changelog updates

.luarc.json
Add json schema link to .luarc.json.
=> Add schema link to .luarc.json.

script/await.lua, script/core/diagnostics/assign-type-mismatch.lua, script/core/diagnostics/need-check-nil.lua, script/core/diagnostics/redundant-value.lua, script/core/diagnostics/trailing-space.lua, script/core/diagnostics/unbalanced-assignments.lua
These 5 diagnostics cause ~70% of all calls to await.delay() by diagnostics which in turn is about ~20% of the total runtime of diagnostics.
Out of these diagnostics only assign-type-mismatch commonly exceeds runtimes of 100ms (worst observed in my dataset was 7 seconds) and even then it still attempts to call await.delay() over 1500 times per second, so throttling by a factor of 15 is still fine.
There are likely more places where await() could be optimized, but the diagnostics are the low-hanging fruit because they are easy to find.
=> Throttle calls to await.delay() in some diagnostics

changelog.md, script/provider/diagnostic.lua
Hi!
I created a new Neovim [plugin](https://github.com/folke/lazydev.nvim) that automatically updates the `workspace/library` configuration for the active workspace folder based on what files the user has open in Neovim.
It works great and is a lot faster than my older `neodev.nvim` plugin.
However, one thing I noticed, is that when I send a `workspace/didChangeConfiguration`, the diagnostics of the currently open files, become all wrong (things like, `string`, or `table` does not exist).
After a couple of seconds, they are then replaced by the correct diagnostics.
After debugging, it seems that diagnostics sometimes run, even when the workspace is not ready.
This PR fixes that.
=> don't do diagnostics when workspace is not ready

script/plugin.lua
Specifically to prevent it from trying to match the tostring-ed numeric number keys of plain arrays with config folder paths, which can lead to false positives if those paths contain numbers and then ultimately results in only a single argument out of the arguments array being passed along
Side note, it's nice for multi plugin to be natively supported, plus separating plugin args like this. Though this is a bug where the plugin args are just an array without any separating which is only useful when there's a single plugin so I suppose it's unrelated but still thank you :D
=> Fix plugin arg arrays when paths contain numbers passing along only one argument

changelog.md, script/core/completion/postfix.lua
Sometimes we are not sure whether functions return a tuple or a table, assuming we need to get a position containing `row` and `col`, wrote:
```lua
local position = get_position()
```
Then we found `position` here is an `integer`, not a `table` (by inlay hint or diagnostic info), which means `get position` returns a tuple. In this situation, a postfix snippet will be useful because our cursor is at the end of the line. By simply typing `@unpack` we can turn it into a tuple.
```lua
local position = unpack(get_position())
```
That's why I think this snippet is useful.
=> Add postfix snippet for `unpack`

changelog.md, doc/en-us/config.md, doc/pt-br/config.md, script/parser/compile.lua
I've implemented support for lambda-style functions. Currently, this is configured by adding `|lambda|` to `Runtime.nonstandardSymbols`. It's trivial to change it to be exposed to the user with a different option, if necessary.
Closes #2515
=> Add support for lambda-style functions

changelog.md, script/cli/check_worker.lua
The default severity when running CLI `--check` is incorrectly set to `'Warning'` if the `diagnostics.severity` config table is incomplete.
This will fix #2730  .
=> fix: default severity in CLI with partial 'diagnostics.severity' config

changelog.md, script/cli/check_worker.lua, script/core/diagnostics/undefined-field.lua, script/vm/def.lua
Recently I am integrating LuaLs into our project's CI and I am looking for ways to speed up the process. The following are 2 simple optimizations that I have found:
I found this recently added **multi-threaded `--check`** in #2638. Upon some code reviewing I suspect that the hash function used to distribute work across multi threads is not that perfect, which limits its full potential. I simply changed it to **Round Robin** (after sorting the file list of course), and this yields another **`10%`** performance gain in my project workspace (500+ lua files). Benchmarks as follow:
- CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
| threads | ori-1 | ori-2 | ori-3 | ori-avg  |   | new-1 | new-2 | new-3 | new-avg  |   | diff |
|---------|-------|-------|-------|----------|---|-------|-------|------ …
=> Perf: Improve performance of multithreaded `--check` and `undefined-field` diagnostic

changelog.md, script/core/completion/completion.lua
This PR fixes the issue that the `showParams` config is not respected when completing local functions. I've attached screenshots to illustrate this problem (with `completion.showParams` set to false)
Before this fix:
After this fix:
=> fix: respect showParams config for local function completion

meta/template/string.lua
常用的写法，第二个参数是函数时，可以不需要关心返回值。因为它的结果已经通过函数的upvalue向外传递。
``` lua
local function split(str)
local r = {}
str:gsub("[^\n]+", function (w) r[#r+1] = w end)
return r
end
```
@sumneko 如果能更智能一点，对第二个参数是函数情形去掉nodiscard，其余情况保留nodiscard。例如这样 
``` lua
---@param s       string|number
---@param pattern string|number
---@param repl    string|number|table
---@param n?      integer
---@return string
---@return integer count
---@nodiscard
function string.gsub(s, pattern, repl, n) end
---@param s       string|number
---@param pattern string|number
---@param repl    function
---@param n?      integer
---@return string
---@return integer count
function string.gsub(s, pattern, repl, n) end
```
=> Remove nodiscard from string.gsub

changelog.md, script/core/hint.lua, script/provider/provider.lua
Basically a cosmetic change. Aligns the parameter inlay hint spacing with that of most other LSPs that I've seen
Before:
After:
=> Align inlay hint spacing with other LSPs

.vscode/tasks.json, changelog.md, script/core/diagnostics/inject-field.lua, test/diagnostics/inject-field.lua
fix related to https://github.com/LuaLS/lua-language-server/issues/2746
=> fix: add a missing check for 'inject-field' diagnostics

changelog.md, script/config/template.lua, script/vm/visible.lua, test/diagnostics/invisible.lua
hi,
this PR add support for lua regular expressions for parameters:
- `Lua.doc.privateName`
- `Lua.doc.packageName`
- `Lua.doc.protectedName`
it also adds a new `Lua.doc.regengine` (the name can be changed) parameter, which can be set to `glob(default)` or `lua`
```json
{
"Lua.doc.protectedName": [
"^_[%w_]*_$"
],
"Lua.doc.privateName": [
"^_[%w_]*%w$"
],
"Lua.doc.regengine": "lua",
}
```
```lua
---@class A
local A = {}
A._id_ = 0 --  is protected
A._user = "bob" -- is private
---@type A
local t
print(t._id_) -- warning
print(t._user) -- warning
---@class B: A
local t2
print(t2._id_) 
print(t2._user) -- warning
```
=> added lua regular expression support for Lua.doc.<scope>Name

changelog.md, script/vm/visible.lua, test/diagnostics/invisible.lua
a quick and dirty modification of getVisibleType to correct this issue:  #2752
=> fix a specific case for getVisibleType

changelog.md, script/library.lua
The PR corrects the `wholeMatch` function, making it work effectively and more efficiently. The addon can self-recommendation as expected now.
The doc recommends writing `words` in `config.json` like this:
```json
"words": [ "require[%s%(\"']+MAA[%)\"']" ]
```
Most addon authors captured the require string in the doc. However, a commit three years ago (`f4e4cc0114adba8d199f9f81298a7c15c9576d5c`) modified the code from:
```lua
if text:match(word) then
...
```
to
```lua
local pos1, pos2 = a:match('()' .. word .. '()')
local left = a:sub(pos1 - 1, pos1-1)
local right = a:sub(pos2, pos2)
...
```
Unfortunately, if the pattern word itself has captures (similar to the doc example), `pos2` will return a string instead of a number. Consequently, the whole self-recommend feature hasn't worked for …
=> Fixed wholeMatch function

changelog.md, script/vm/compiler.lua
this will fix #2758 
bug explanation in this comment: https://github.com/LuaLS/lua-language-server/issues/2758#issuecomment-2232618218
=> fix: inconsistent type narrow due to outdated node caches of call.args

changelog.md, script/vm/operator.lua, test/type_inference/common.lua
#2777 
if vm.runOperator fails try again with flipped arguments
this emulates how lua checks the binary metaevents in which
if there is no corresponding binary metaevent for the left
operand it checks the right operand instead. This also works
when both operands are tables.
example case:
```lua
---@class Vector3
---@operator add(number): Vector3
Vector3 = {}
---@type number
local x
local a = x + Vector3
-- type of a is now Vector3
```
This change affects:
- __add
- __sub
- __mul
- __div
- __idiv
- __mod
- __pow
- __concat
- __band
- __bor
- __bxor
- __shl
- __shr
Credit to tomlau10 for preliminary code
=> feat: flip binary operator check if failed (#2777)

script/service/service.lua
The previous hello jsonrpc message caused sadness
since it caused lsp clients to exit as it was not
a correct way to say hello.
closes: #2797
=> FIX: Changed hello param to valid JSONRPC

changelog.md, script/core/definition.lua
E.g. if the current document has path `c/file.lua` and the results have paths:
- `c/file.lua`
- `a/file.lua`
Prefer `c/file.lua` since that is most similar to the current document.
---
Real world example used these paths:
From `/Users/lewis/projects/neovim/runtime/lua/vim/lsp/handlers.lua` with results (in order):
- `/Users/lewis/.cache/lua-language-server/meta/LuaJIT en-us utf8/builtin.lua`
- `/Users/lewis/projects/neovim/runtime/lua/vim/lsp/handlers.lua`
=> fix: improve textDocument/definition ordering

script/cli/check.lua
=> Fix lua-language-server --check (#2683)

changelog.md, meta/template/basic.lua
The first parameter got parsed as `async fun(...):(...|integer)` which triggered an incorrect warning when using it as `setfenv(2, env)`
=> Fix setfenv definition

changelog.md, script/plugin.lua, script/vm/compiler.lua, test/plugins/node/test.lua, test/type_inference/init.lua
closes #2831 
This pull request fixes VM.OnCompileFunctionParam and its test case.
I had the StyLua autoformatter on so some formatting changes were made to compiler.lua. I'm not sure if this is a problem, as I had just assumed this project was StyLua compliant and I was expected to have the formatter running.
=> Fix VM plugins

changelog.md, script/vm/compiler.lua, script/vm/function.lua, test/type_inference/param_match.lua
fix #2509, fix #2708, fix #2709
(this logic has to be based on #2822, otherwise might cause other issues in type narrow behavior)
When a function only has `@overload` annotation, the function itself will auto infer its params' type by using **only the 1st overload type**, combined with the **return type** of the function body logic, thus create an incorrect **base function** when doing function match.
```lua
---@overload fun(a: 1): string
---@overload fun(a: 2): number
local function f(a) end --> fun(a: 1): nil
-- here the `a` in `f()` are inferred by the 1st `@overload` -> `a: 1`
-- and then it combines the return type `nil` due to the empty function body
-- => overall gives an incorrect `fun(a: 1): nil` as the base function signature
local r = f(1)  --> string|nil, bad
-- because it …
```
=> Fix incorrect function params' type infer when there is only `@overload`

changelog.md, script/core/completion/completion.lua
to achieve this bug requires function overloading and multiple variable assignment.
```lua
---@return string, number
---@overload fun(s: "test", a?:number):name:"name", string
function test() end
local name, aString = test("|") --- can see "test" and "name", only "test" is expected
```
using the debugger I go back to the `findNearestSource` function which does not see the correct source.
`guide.eachSourceContain` only returns the same source once, so you need to check if it is closer.
```lua
local function findNearestSource(state, position)
---@type parser.object
local source
guide.eachSourceContain(state.ast, position, function (src)
if not source or source.start <= src.start then
source = src
end
end)
return source
end
```
=> Fix correctly display enums for function overload arguments

changelog.md, script/lclient.lua, script/provider/provider.lua
Happy first birthday, issue #2318!
During its first year of existance, issue #2318 has failed to get any attention at all from the project maintainers. Even though it addresses a fundamental bug. A couple of people have commented that the patch has helped them, from which we can derive that probably many more are using the patched version without bothering to comment.
Not that I believe the existence of a pull request will change anything, but lets give this a try.
As previously communicated, I do not read simplified chinese. So someone else will need to update the remaining test cases or translate and rework the explanatory comments into English. Disabling or removing broken tests would be an option as well, of course. Yet, then again, with other tests already failing on master one might …
=> Only call workspace/configuration when available

script/core/completion/completion.lua
fixes https://github.com/LuaLS/lua-language-server/issues/2762
after analysis in https://github.com/LuaLS/lua-language-server/issues/2762#issuecomment-2335089712
=> fix(completion): remove logic causing wrong text edits

script/vm/compiler.lua
https://github.com/LuaLS/lua-language-server/issues/2573
This change handles "cannot be injected" correctly if the field member is inherited.
```lua
---@class (exact) A
---@field test number
local a = {}
function a:init()
--This is fine
self.test = 0
end
---@class (exact) B : A
local b = {}
function b:init()
--This is an injection and thus invalid
self.test = 0
--This is an actual injection and will remain invalid
self.test2 = 0
end
```
=> Fixed injects into child classes

changelog.md, make.bat, make.sh
These scripts call the newly compiled luamake binary directly as `3rd/luamake/luamake` so there's no need for it to be installed or added to the user's PATH globally and permanently.
More generally, the `make` command for a single project should not be writing to the user's `.bashrc` or `.zshrc`.
=> Remove luamake install from make.sh and make.bat

changelog.md, test/full/projects.lua, test/full/self.lua
Floating point error causes some test benchmark times to have a bunch of trailing 9s or 0s before some noise at the end.
Before:
```
诊断文件耗时：  0.0048709999999978      file:///Users/sparr/src/lua-language-server/script/SDBMHash.lua
诊断文件耗时：  0.545929        file:///Users/sparr/src/lua-language-server/script/await.lua
诊断文件耗时：  0.0079290000000007      file:///Users/sparr/src/lua-language-server/script/brave/log.lua
```
After:
```
诊断文件耗时：  0.004871        file:///Users/sparr/src/lua-language-server/script/SDBMHash.lua
诊断文件耗时：  0.545929        file:///Users/sparr/src/lua-language-server/script/await.lua
诊断文件耗时：  0.007929        file:///Users/sparr/src/lua-language-server/script/brave/log.lua
```
=> Use `string.format` to fix floating point error in test output

changelog.md, script/core/diagnostics/duplicate-set-field.lua, script/vm/compiler.lua, test/diagnostics/duplicate-set-field.lua, test/type_inference/common.lua
resolves #2158, https://github.com/LuaLS/lua-language-server/issues/2569#issuecomment-2342854384
Sometimes we will want to define interface for overriding in **instance object of that class**, and retain the param types defined in the interface while overriding. But currently no way to do so as described in #2158 and https://github.com/LuaLS/lua-language-server/issues/2569#issuecomment-2342854384
```lua
---@class A
local A = {}
---@return A
function A.new() end
---@param x number
function A:user_callback(x) end
local a = A.new()
function a:user_callback(x) end -- no type infer for `x`, also throwing `duplicate-set-field` warning
```
Detailed explanation here: https://github.com/LuaLS/lua-language-server/issues/2569#issuecomment-2350869680
```lua
---@class A
local A = {}
---@return A …
```
=> Infer function parameter types when overriding the same-named class function in an instance of that class

changelog.md, script/vm/tracer.lua, test/type_inference/common.lua
```lua
---@class A
---@field type 'a'
---@class B
---@field type 'b'
local obj --- @type A|B
if obj.type == 'a' then
-- obj is narrowed to type A
end
```
Currently only narrows types defined with `@class`. I attempted to make this work for `@alias` (as in https://github.com/LuaLS/lua-language-server/issues/704) but it got rather complicated.
It may be beneficial to cache the result of `getNodeTypesWithLiteralField`.
=> feat: type narrow types with literal fields

changelog.md, script/files.lua
Finally doing what was [promised long ago](https://github.com/LuaLS/lua-language-server/discussions/1950#discussioncomment-7547044) and adding an `${addons}` variable/placeholder for paths so that people can specify, for example, `${addons}/busted/module/library` and it will resolve to the installation location for the addon manager.
There are a lot of different platforms, which I could not all test myself. I have tested a few though:
The proper solution is probably to change the installation location for addons from the addon manager to go to `~/.luals/addons` rather than wherever VS Code has decided to throw them. It would then hopefully be much easier to find them and would be less dependent on VS Code. Something to keep in mind for the new addon manager, but unlikely to be implemented …
=> add: placeholder for ${addons} for paths

script/vm/tracer.lua, test/type_inference/common.lua
This shouldn't need a changelog entry since there hasn't been a release since the bug was introduced.
=>  fix: type narrow on fields with multiple literals

changelog.md, script/files.lua
This is an alternative to #2892 following the suggestion to allow the client to tell the server where addon files should be stored. I again memoized the result to avoid looking it up many times.
Matching PR on the other side: https://github.com/LuaLS/vscode-lua/pull/150
I have tested this on EndeavourOS (~Arch Linux), but cannot currently test on mac or windows.
=> Add storagePath handling and memoization to resolvePathPlaceholders

changelog.md, script/core/hover/description.lua
FIXES #2887 
Thanks to @tomlau10 for this idea.
I've tested in a few scenarios and the results are promising. `@see` is still appended without a newline if there's comment content above it and no params to separate them in the rendered output, but an explicit empty comment line above it will force it onto its own new line. Making it always on a new line may be preferable, but that would be a bigger change.
=> Return markdown from getFunctionComment to temporarily preserve trailing newlines

changelog.md, script/vm/compiler.lua, test/type_inference/common.lua
While giving reply in an old issue, I found a regression issue related to `@overload` and `@generic`: https://github.com/LuaLS/lua-language-server/issues/723#issuecomment-2408837943
After doing **git bisect**, I found that it is introduced in this commit of `v3.10.1` : https://github.com/LuaLS/lua-language-server/commit/8ecec08
```lua
---@generic T
---@param v T
---@return T
local function f1(v) end
local r1 = f1(1) --> integer, good
---@generic T
---@param v T
---@return T
---@overload fun(): nil
local function f2(v) end
local r2 = f2(1) --> unknown, bad
```
```lua
---@generic T
---@param v T
---@return T
---@overload fun(): nil
local function f2(v) end
local r2 = f2(1) --> integer, good
```
---
我在回覆一個舊 issue 的時候，發現一個關於 `@overload` 及 `@generic` 的 regression 問題，具體例子見上邊。
大概是當 function 同時有 …
=> fix: regression related to type narrow and generic since v3.10.1

changelog.md, script/vm/type.lua, test/type_inference/common.lua
Big thanks to @tomlau10 for basically writing the fix for me.
After some testing and trying any weird thing I could think of to break the fix, it seemed pretty bulletproof, but I wouldn't be surprised if I'm just not creative enough.
I went ahead and added a test and an entry to the changelog.
This is my first time contributing to luals, so I'd love constructive feedback. Like I feel like my wording is bad no matter how I think about wording things :grin:
FIXES #2906
=> Fix vararg indices being unknown when iterated

changelog.md, script/vm/ref.lua, test/references/all.lua
We had a problem that in this code:
```
---@class A
---@field x number
---@type A
local a = {
x = 4
}
```
VSCode can't find this reference. 
After fixing it, it works fine : )
=> [reference] Check also in tablefield

changelog.md, script/files.lua
I am not sure if this is 100% necessary in order to fix https://github.com/LuaLS/vscode-lua/issues/154… but it should help add more safety, should VS Code choose to provide or not provide a trailing slash for the storage path.
Related client PR: https://github.com/LuaLS/vscode-lua/pull/156
=> fix: parse storage path

changelog.md, script/core/code-action.lua, script/core/command/autoRequire.lua, script/core/completion/auto-require.lua, test/command/auto-require.lua
例如:
键入`Currency`会提示导入`local Currency = require("schema").player.Currency`
=> [New] `enum`现在允许在快速修复中导入.

changelog.md, script/config/template.lua, script/vm/type.lua
```lua
local t1 = {
[1] = {
x = 1
},
[2] = {
x = "test"
}
}
local t2 = {
{
x = 1
},
{
x = "test"
}
}
local idx = 2
local a = t1[idx]
local b = t2[idx]
```
让我们键入以上的代码，我认为t1和t2两个数组的结果是一样的，但是结果是变量a和变量b的提示并不一样。
变量a给我的代码提示是我能够接受的，
但是b给我的代码提示是错误的，始终把`local b = t2[idx]`等价解析为`local b = t2[1]`，这并不完全正确，
通过阅读源码，我并不知道为什么针对tableexp类型还要加上`field.tindex == 1`这样的判断，但将其去除后代码提示就正确了。
=> Fix table array infer

changelog.md, script/core/signature.lua, script/vm/compiler.lua, test/completion/common.lua, test/signature/init.lua
This supports type narrow during **completion** and **signature help** when function params are using `@alias` with literal values, as requested here: https://github.com/LuaLS/lua-language-server/issues/1456#issuecomment-2439765409
Example use case:
```lua
---@alias events.AAA
---| "AAA" # description to AAA
---@alias events.BBB
---| "BBB" # description to BBB
---@class Emitter
---@field on fun(self: self, event: events.AAA,  cb: fun(a: integer))
---@field on fun(self: self, event: events.BBB, cb: fun(b: string))
local Emitter = {}
Emitter:on('BBB', <??>) --< trigger completion will suggest `fun(b: string)`, instead of showing both
```
上述 issue comment 作者想用 `@alias` 來定義 event name，因為這樣可以對 enum value 加 description，但發現用 alias 後做 completion 時無法做 type narrow。
這個 PR 是想在做 completion 和 signature …
=> fix: improve type narrow with literal alias param during completion and signature help

changelog.md, locale/en-us/setting.lua, locale/ja-jp/setting.lua, locale/pt-br/setting.lua, locale/zh-cn/setting.lua, locale/zh-tw/setting.lua, script/config/template.lua
https://github.com/LuaLS/vscode-lua/pull/158
=> config: add custom repository support for addonManager

changelog.md, script/vm/compiler.lua, test/type_inference/common.lua
closes #2695 (the feature request by **me**, finally I have the knowledge to implement myself 🙂 )
- This supports inferring function param type when the **local function** is used as **call argument**, and that the argument has a `fun()` annotation.
- This is actually an improvement to the existing `Lua.type.inferParamType` logic, so this feature is only enabled when this config is set to `true`.
```lua
---@param callback fun(a: integer)
function register(callback) end
local function callback(a) end  --> a: integer
register(callback)
```
which is similar to existing infer behavior with function literal:
```lua
register(function (a)  --> a: integer
end)
```
---
- 具體應用例子見上邊
- 在效果上來說跟現有的 function literal infer param type 基本相同，只不過是應用到 **local function** 的 param 上
- 這個算是對現有 …
=> feat: infer function param when the function is passed as call arg

changelog.md, script/vm/type.lua
fix that
```shell
[Error - 12:44:58 PM] Request textDocument/semanticTokens/range failed.
Message: [12:44:56.481][error][#0:script/vm/type.lua:341]: script/vm/type.lua:341: attempt to get length of a nil value (local 'errs')
stack traceback:
script/vm/type.lua:341: in function <script/vm/type.lua:287>
(...tail calls...)
script/vm/type.lua:461: in function 'vm.vm.isSubType'
script/vm/type.lua:372: in function 'vm.vm.isSubType'
script/vm/type.lua:785: in function 'vm.vm.canCastType'
script/vm/function.lua:349: in upvalue 'isAllParamMatched'
script/vm/function.lua:363: in upvalue 'calcFunctionMatchScore'
script/vm/function.lua:400: in function 'vm.vm.getExactMatchedFunctions'
script/vm/compiler.lua:611: in upvalue 'matchCall'
script/vm/compiler.lua:2278: in function 'vm.vm.compileNode' …
```
=> fix: add missing `errs ~= nil` checks to script/vm/type checkTableShape

changelog.md, script/core/diagnostics/missing-fields.lua, test/diagnostics/missing-fields.lua
Should close #2337, close #2598, close #2740, close #2966
=> Fix missing-fields diagnostic not warning about missing inherited fields

changelog.md, script/parser/guide.lua, script/vm/compiler.lua, test/type_inference/common.lua
fix #2367
bugfix explanation:
- `{ function() end }` is parsed as `tableexp`
but it is not considered as **assign type**
=> so it is not receiving type infer from `---@type {[integer]: fun()}` annotation
https://github.com/LuaLS/lua-language-server/issues/2367#issuecomment-2310196191
- the `---@type fun()[]` annotation is giving out `doc.type.function` when inferring `tableindex` operation
but is ignored by the current logic
=> so `{ [1] = function () end }` cannot receive type infer
https://github.com/LuaLS/lua-language-server/issues/2367#issuecomment-2538834404
=> fix: incorrect infer of function array annotation on tables

changelog.md, locale/en-us/setting.lua, locale/ja-jp/setting.lua, locale/pt-br/setting.lua, locale/zh-cn/setting.lua, locale/zh-tw/setting.lua, script/config/template.lua, script/vm/doc.lua
This option is disabled by default.
When disabled, it has no impact on performance.
When enabled, --@async propagates to the caller.
=> add setting`Lua.hint.awaitPropagate`

changelog.md, script/provider/provider.lua
This is useful to be able to display the version of the currently attached server. See https://github.com/neovim/neovim/pull/31611 for example.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeResult
=> Add `serverInfo.version` to `initialize` response

script/provider/provider.lua
Per LSP specification, `insertTextFormat` should be `2` for snippets and `1` for plain text. Using `2` unconditionally can make clients behave in unexpected ways. For example, the `nvim-cmp` plugin for Neovim doesn't properly handle the case of completion inside of a snippet when `insertTextFormat` is incorrect.
The code calling into `provider.lua` sets `insertTextFormat` to 2 for all snippets and leaves it nil for other types, so we can reuse that information in `provider.lua` to make sure we send the correct value.
This was previously brought up in #992, but the closing PR didn't resolve the issue directly.
=> Send the correct `insertTextFormat`

changelog.md, script/cli/doc/init.lua, script/lclient.lua, script/provider/provider.lua
fixes #3008, fixes #2997
Follow-up on my issue #3008 .Screenshots of some of the effects can also be found in the issue.
This commit is intended to fix a bug where exporting a document via the command line could not read the configuration file specified with the '--configpath' option.
from: [#2997](https://github.com/LuaLS/lua-language-server/issues/2997#issue-2749438160)
[.luarc.doc.json](https://github.com/user-attachments/files/18261936/default.luarc.doc.json)
``` shell
./bin/lua-language-server.exe --configpath ./.luarc.doc.json --doc ./test/main.lua --doc_out_path ./test/
```
``` lua
M = {}
```
[doc.json](https://github.com/user-attachments/files/18261929/doc.json)
``` shell
root uri        file:///e%3A/luals/old/test/main.lua
Config All Path:        E:/luals/old/.luarc.doc.json …
```
=> Fixed the error that the configuration file pointed to by the `--configpath` option was not read and loaded.

script/core/completion/completion.lua
The PR #3005 assumed that all snippets were setting `insertTextFormat` to 2 and leaving plaintext completions nil, but that was not the case. Function completions need to be marked as snippets too.
fixes #3021
=> Mark function completion items as snippets

changelog.md, script/core/diagnostics/missing-fields.lua, test/diagnostics/missing-fields.lua
resolves #3023, resolves #2561
---
Since #2970, the partial class "hack" for not checking missing inherited fields no longer works.
This PR brings back this feature by introducing a `partial` attribute for `@class`.
A class marked with `partial` will not check missing inherited fields, just like the original checking behavior.
```lua
---@class Config
---@field a number
---@class (partial) Config.P: Config
---@field b number
---@type Config.P[]
local cfgs = {}
cfgs[1] = { b = 1 } -- no warning
cfgs[2] = {}        -- only warns missing `b`
```
自 #2970 起，原有的 partial class hack 被封了。
這個 PR 對 `@class` 簡單地引入 `partial` 屬性
=> 帶 `partial` 屬性的 class 在檢查 missing fields 時會忽略 inherited class 的字段，就像之前的 check logic 一樣
=> Basic `partial` class support

changelog.md, script/core/semantic-tokens.lua, script/parser/compile.lua, script/parser/luadoc.lua, script/vm/sign.lua
~~The positions were calculated slightly incorrectly there, because it got confused with the lengths.~~
```
---@param a string?Comment
local function new(a) end
---@param a string[]Comment
local function new(a) end
```
now its `Comment` instead of `omment`.
~~But I came across the fact that the comment texts `comment.text` do not contain `--` at the beginning, because this token is uuuh... being skipped?~~
~~That is, we were working with a string of a different length and start pos (-2). I made a variable `local textOffset = 2` so that it could be easily fixed in the future.~~
~~p.s. Maybe you should figure out why this is happening.~~
=> LuaDoc. Fixed the start position of the comment first symbol in docs

changelog.md, script/parser/luadoc.lua
fixes #2673 
這個是我上年最初接觸和使用 luals 時遇到的一個問題
當時由於找到繞過方式用 `@type`，也就解決了
但是最近自某版本起 `@type` 修正成會檢查該 class 的所有 **missing field** 而導致報錯。。。
- 要麼用 disable 方式忽略部分報錯
- 要麼改回用 `@class`
後者好像合理一些
換句話還是得解決最根本的問題：
**連續多行用 tail comment 寫 `@class` 時，無法正確 bind 到 variable**
最初由於不了解 luals 代碼庫，所以也沒有深究原因
現在算是稍為熟悉一點了，很快找到 fix 方式了 🙂
=> fix: bind variables with `@class` using tail comments

script/core/completion/postfix.lua
Similar to 3e0d1df. Postfix items should be marked as snippets.
=> Mark postfix completions as snippets

changelog.md, script/vm/infer.lua
fixes https://github.com/LuaLS/lua-language-server/issues/3049
=> Avoid truncating output in ---doc mode

changelog.md, locale/en-us/script.lua, locale/ja-jp/script.lua, locale/pt-br/script.lua, locale/zh-cn/script.lua, locale/zh-tw/script.lua, script/cli/check.lua, script/cli/check_worker.lua, script/global.d.lua
Adds a new CLI option --check_format which accepts the values: 'json'
(current behaviour), and a new 'pretty' value which prints a colorized
human readable report to stdout, similar to common compilers and
linters.
Results are printed with color unless NO_COLOR is defined in the users
environment, as per https://no-color.org.
If --check_out_path is provided, then the results are always saved to
file regardless of the --check_format value.
I've made `pretty` the default format, however to mitigate against any breakage I've made it also write the json files with `--check_out_path` is provided, so this will be like enabling both formats at once.
- Outlined some functions in `check_worker.lua`.
- Made `--quiet` work properly with `--num_threads`
=> feat: add --check_format=json|pretty

changelog.md, script/files.lua, script/provider/provider.lua, script/workspace/scope.lua, script/workspace/workspace.lua
resolves #2987 
---
implementation details: https://github.com/LuaLS/lua-language-server/issues/2987#issuecomment-2603462641
- workspace folder names are captured from client's initialization request param `workspaceFolders[].name`
- if provided, it is then stored into the created `workspace.scope` object
- finally when resolving a `${workspaceFolder:x}` path placeholder
use the decoded `uri` of the `workspace.scope` object that having `x` as the folder name
(which becomes absolute path of that folder)
- a dummy `_.code-workspace`
```jsonc
{
"folders": [
{
"name": "root",
"path": "."
},
{
"name": "client",
"path": "client"
},
{
"name": "server",
"path": "server"
}
],
"settings": {
"Lua.workspace.library": [
"${workspaceFolder:client}",
]
}
}
```
- upon inspecting log file, the client is …
=> feat: add variable substitution support for vscode's `${workspaceFolder:x}`

changelog.md, script/vm/compiler.lua, test/completion/common.lua, test/completion/init.lua
fixes #2196, fixes #2945
resolves #3041 (fixing this bug fulfills the requirement of that issue, such that the feature request becomes unnecessary)
---
Bug explanation: https://github.com/LuaLS/lua-language-server/issues/2945#issuecomment-2466563177
```lua
---@class Array<T>: { [integer]: T }
---@field private length integer
local Array
function Array:push()
self.  --> suggest `length`, `push(self)`
end
---@type Array<string>
local a
print(a.length) --> Field `length` is private, it can only be accessed in class `Array`.
a: --> suggest `push()`
```
CppCXY's new lua language server written in rust has better generic support 😃 
- https://github.com/LuaLS/lua-language-server/issues/3017
---
簡單在 `searchFieldSwitch` 增加對 `doc.type.sign` 的支持，以修復 generic class object 沒有 field completion 的問題。 …
=> fix: missing field completion for generic class object

changelog.md
I'm sorry, but I wrote the wrong link format in my pull request.
Now I've made beautiful links, and added a second one. I also clarified a previous one.
You can publish it in the next release, because it's almost nothing.
p.s. In fact, you don't have to write the full markdown link for **VS Code**, because it somehow guessed that the `#\d+` format its a link to `[extension repo]/issues/` (yeah not a `/pull/` but still works for github)
but since its not just for **VS Code**, I think its better to use the full markdown link format.
=> Fix changelog links

changelog.md, script/cli/check.lua
(first thing first, this bug is **NOT** introduced by recent changes)
With https://github.com/LuaLS/lua-language-server/pull/3051, now the default check output format is `pretty`.
But I also want to parse the `check.json`, so I added `--check_out_path=xxx` option is my team's project CI:
```bash
${LUALS_PATH}/bin/lua-language-server --check=. --check_out_path=${LUALS_RESULT_FILE} --num_threads=2 --checklevel=Error
```
- But after adding the `--check_out_path=`, I then found that `--num_threads=2` seems not working 😳 
- However if I add `--check_out_path=` at the **end**, it will work 🙄 
```bash
${LUALS_PATH}/bin/lua-language-server --check=. --num_threads=2 --checklevel=Error --check_out_path=${LUALS_RESULT_FILE}
```
Upon investigation, I found that the `--num_threads` argument is not …
=> fix: incorrect arg skip pattern for `--check_out_path=`

changelog.md, script/cli/check_worker.lua
When using `--check=.` there will be a `./` in the file path, both in the pretty report and json.
```
tomlau10@TOMLAU-PC /mnt/c/Users/TomLau/test
$ lua-language-server --check=. --check_out_path=check.json
./main.lua:1:10 [Warning] Undefined type or alias `MyClass`. (undefined-doc-name)
---@type MyClass
^^^^^^^
Diagnosis complete, 1 problems found, see check.json
tomlau10@TOMLAU-PC /mnt/c/Users/TomLau/test
$ cat check.json | grep file
"file:///mnt/c/Users/TomLau/test/./main.lua": [
```
This exists long ago, and I have been using **jq**'s `sub("^.*?\\./"; "")` when parsing the `check.json` in CI environment.
Today my curiosity led me to investigate this issue, and I found the root cause:
- current logic is using `fs.absolute()` from `bee.filesystem` to convert the input argument …
=> fix: remove extra `./` prefix in check report when using `--check=.`

changelog.md, script/cli/doc/export.lua, script/cli/doc/init.lua
Fixes #2971
File names in doc.json were broken since #2821.
=> fix: incorrect file names in doc.json

changelog.md, script/cli/doc/export.lua
Fixes #2963
Reimplements section `luals.config` in file doc.json that was missing since #2821.
=> fix: reimplement section luals.config in doc.json

changelog.md, script/cli/doc/init.lua
Fixes #3073
Back then the default path of doc.json was LOGPATH. However the default path got lost after a refactoring in #2821. This commit reimplements the default path, but changes the default to the current directory.
=> fix: default path for --doc_out_path is the current directory

meta/template/os.lua
Using `os.time()` with an `osdate` type input is currently not allowed, only `osdateparam` is allowed.
```lua
---@type osdate
local date
dosomething(os.time(date))
--- Cannot assign `osdate` to parameter `osdateparam?`.
--- - `osdate` cannot match `osdateparam?`
--- - Type `osdate` cannot match `nil`
--- - Type `osdate` cannot match `osdateparam`Lua Diagnostics.(param-type-mismatch)
```
This simple change makes so that `osdate` is a child of `osdateparam`, and as such can be used in all curcumstances an `osdateparam` would be acceptable.
=> fix: osdate is not allowed in `os.time`

changelog.md, script/cli/help.lua, script/cli/init.lua, script/global.d.lua
Content copied from https://luals.github.io/wiki/usage/
<details>
<summary>Preview</summary>
```
./bin/lua-language-server --help
--socket=<value>
Will communicate to a client over the specified TCP port instead of through stdio.
Type: number
Example: --socket=5050
--develop
Enables development mode. This allows plugins to write to the logpath.
Type: boolean
--force-accept-workspace
Allows the use of root/home directory as the workspace.
Type: boolean
--configpath=<value>
The location of the configuration file that will be loaded.
Can be relative to the workspace.
When provided, config files from elsewhere (such as from VS Code) will no longer be loaded.
Type: string
Example: --configpath=sumnekoLuaConfig.lua
--loglevel=<value>
The minimum level of logging that should appear in the …
```
=> feat: add --help

changelog.md, script/vm/compiler.lua, test/type_inference/common.lua
fixes #3087
debugging and explanation: https://github.com/LuaLS/lua-language-server/issues/3087#issuecomment-2676653835
- `3.10.1` 中 https://github.com/LuaLS/lua-language-server/commit/8ecec08 的改動應該是有問題
目前出現另1個 regression issue 跟這改動有關
- 具體問題原因我還沒搞清楚
不過現在回看，該 fix 實際上過於複雜了 😂 
- https://github.com/LuaLS/lua-language-server/commit/8ecec08 是為了修正 #2776 
而 issue 2776  的主要問題，似單純是 **如果某 arg node 已經 compile 過，說明在相同 callstack 後邊需要被引用**
=> 不能單純做 remove，否則會導致 **error: index nil value**
=> 換句話其實在 remove 後直接 recompile 一次應該就可以 🤔
=> fix: another regression related to type narrow and generic since v3.10.1

changelog.md, meta/template/bit.lua
Specifically for function `bor`, `band` and `bxor`, which all only
require one mandatory argument.
Reference: https://bitop.luajit.org/api.html
=> fix: fix type annotations for bit module

changelog.md, locale/en-us/meta.lua
The links for the string methods were pointing to a non-existent url.
This was because the section 6.4.1 doesn't exist for lua 5.1, but rather 5.4.1 has
the pattern section.
=> fix: correct pattern links for string methods

changelog.md, meta/template/math.lua
`math.type` and `math.ult` were added in Lua 5.3. The annotations for these functions didn't reflect this.
=> Correct version for `math.type` and `math.ult`

changelog.md, script/cli/help.lua
=> Chore: Update help messages

changelog.md, make.lua
This PR fixes the `--dbgport=xxx` option not working in Linux. The following could be seen in the logs:
```
$HOME/.vscode/extensions/actboy168.lua-debug-2.0.12-linux-x64/runtime/linux-x64/lua54/luadebug.so: undefined symbol: lua_getmetatable
```
This error comes from the fact that the host process (lua language server) does not expose lua54 symbols for `luadebug.so` to use.
The fix adds a compilation flag that will be used by `luamake` and will incorporate those symbols.
=> [fix] Linux debugging server not starting

changelog.md, script/core/color.lua
I am using neovim, and neovim recently got support for `textDocument/documentColor`.
I also have a colortheme defined in my config, where I have a bunch of hex colors like `#a6e3a2`. It would be really nice if this server could support the colors in this format😅
This PR adds support for this, and seems to be working pretty good for me
Before:
After:
=> feat: support hex color with `#`

changelog.md, locale/en-us/setting.lua, locale/es-419/setting.lua, locale/ja-jp/setting.lua, locale/pt-br/setting.lua, locale/zh-cn/setting.lua, locale/zh-tw/setting.lua
With a new hyperlink, serval typo fixing and simplified Chinese translation.
=> docs: add missing locale.

changelog.md, doc/en-us/config.md, doc/pt-br/config.md, doc/zh-cn/config.md, doc/zh-tw/config.md, locale/en-us/setting.lua, locale/es-419/setting.lua, locale/ja-jp/setting.lua, locale/pt-br/setting.lua, locale/zh-cn/setting.lua, locale/zh-tw/setting.lua, script/config/template.lua, script/files.lua, script/workspace/workspace.lua
This pull request enables users to specify a custom addons path for 3rd-party libraries, addressing the current limitation where only the VSCode-addons path is used.
Highlights:
- Adds `files.updateAddonsPath` to let users update the `addonsPath` if it has not been configured already.
- Validates the provided path using `fs.exists` after expanding it via `util.expandPath`.
- Extends the language server's usability beyond VSCode to support editors like Vim/Neovim.
Currently the configuration `Lua.addonRepositoryPath` has a higher priority, but if it's not set, it won't affect the addon manager in vscode.
Example:
1. Clone the addon repo, let's say the command is execute under `/tmp` so a folder `/tmp/LLS-addons` will be created with all the submodules.
```bash
git clone …
```
=> Support Custom Addons Path for Enhanced Editor Flexibility

changelog.md, script/config/template.lua, script/vm/type.lua
Close #3178 and close #3126 by adding a config option `Lua.type.maxUnionVariants` to control how many union variants a value is checked against. By default, the setting is set to 0, meaning that the language server will check all union variants. 
Further work to improve ergonomics with this setting might include adding a warning when a union type is defined that has too many variants.
=> fix: large unions no longer erroneously fail to match later variants

changelog.md, script/config/template.lua
This pull request adds the `|lambda|` operator to the Lua.runtime.nonstandardSymbol configuration template, which allows the use of that option. Previously, support for it existed in the parser, but we could not actually use the option because it is not recognised in the configuration.
=> feat: add '|lambda|' to nonstandardSymbol in template

changelog.md, script/core/diagnostics/inject-field.lua
I found this display bug while discussing in an issue: https://github.com/LuaLS/lua-language-server/issues/3211#issuecomment-3008185862
```lua
---@class (exact) A
---@field a integer
local A = {
b = 1,  --> Fields cannot be injected into the reference of `A` for `A`.
}
```
=> the msg incorrectly uses class name `` `A` for `A` ``
```lua
---@class (exact) A
---@field a integer
local A = {
b = 1,  --> Fields cannot be injected into the reference of `A` for `b`.
}
```
=> the correct msg should be using the field name `` `A` for `b` ``
=> fix: incorrect inject field message for exact class extra field

changelog.md, script/provider/provider.lua
Nvim show me an error(since: https://github.com/neovim/neovim/pull/34789), when I hover an symbol
whose definition cannot be found by luals
```
**/neovim/runtime/lua/vim/lsp/util.lua:1685: 'width' key must be a
positive Integer
```
To reprodunce, hover on a with this file
```lua
---@type a
```
Haven't reproduced with other lsp but I think it's harmless to PR here.
=> fix: don't return empty hover
